postgres:
  user: "postgres"
  dbName: "khan"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

mongodb:
  enabled: false
  url: mongodb://localhost:27017
  databaseName: "khan"
  collectionTemplate: "clans_%s"

search:
  pageSize: 50

khan:
  maxPendingInvites: -1
  defaultCooldownBeforeInvite: 0
  defaultCooldownBeforeApply: 3600

healthcheck:
  workingText: "WORKING"

webhooks:
  timeout: 500
  workers: 5
  statsPort: 9999
  runStats: true

jaeger:
  disabled: true
  samplingProbability: 0.001
  serviceName: "khan"

redis:
  host: 0.0.0.0
  port: 6379
  database: 0
  pool: 30
  password: ""

extensions:
  dogstatsd:
    host: localhost:8125
    prefix: khan.
    tags_prefix: ""
    rate: 1

caches:
  getGame:
    ttl: 1m
    cleanupInterval: 1m
  clansSummaries:
    ttl: 1m
    cleanupInterval: 1m
