postgres:
  user: "postgres"
  dbName: "khan"
  password: "123456"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

mongodb:
  enabled: true
  url: mongodb://localhost:27017
  databaseName: "khan"
  collectionTemplate: "clans_%s"

search:
  pageSize: 50

webhooks:
  timeout: 500
  workers: 5
  statsPort: 9999
  runStats: true
  logToBuf: false

healthcheck:
  workingText: "WORKING"

jaeger:
  disabled: false
  samplingProbability: 1.0
  serviceName: "khan"

redis:
  host: 0.0.0.0
  port: 6379
  database: 0
  pool: 30
  password: ""

extensions:
  dogstatsd:
    host: localhost:9125
    prefix: khan.
    tags_prefix: ""
    rate: 1

loadtest:
  game:
    membershipLevel: "member"
    maxMembers: 50
  client:
    url: "http://localhost:8080"
    gameid: "epiccardgame"
  operations:
    amount: 1
    interval:
      duration: "1s"
    updateSharedClanScore:
      probability: 1
    createPlayer:
      probability: 1
    createClan:
      probability: 1
      autoJoin: "false"
    retrieveClan:
      probability: 1
    leaveClan:
      probability: 1
    transferClanOwnership:
      probability: 1
    applyForMembership:
      probability: 1
    selfDeleteMembership:
      probability: 1
    searchClans:
      probability: 1
    retrieveClansSummaries:
      probability: 1

caches:
  getGame:
    ttl: 1m
    cleanupInterval: 1m
  clansSummaries:
    ttl: 1m
    cleanupInterval: 1m
