postgres:
  user: "khan"
  dbName: "khan"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

mongodb:
  enabled: false
  url: mongodb://localhost:27017
  databaseName: "khan"
  collectionTemplate: "clans_%s"

search:
  pageSize: 50

webhooks:
  timeout: 2
  workers: 5
  statsPort: 9999
  runStats: true
  logToBuf: false

healthcheck:
  workingText: "WORKING"

newrelic:
  key: ""

jaeger:
  disabled: true
  samplingProbability: 0.001

redis:
  host: 0.0.0.0
  port: 50505
  database: 0
  pool: 30
  password: ""

extensions:
  dogstatsd:
    host: localhost:9125
    prefix: khan.
    tags_prefix: ""
    rate: 1
