postgres:
  user: "postgres"
  dbName: "khan"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  enabled: true
  host: "localhost"
  port: 9200
  sniff: false
  index: "khan"

healthcheck:
  workingText: "WORKING"

newrelic:
  key: ""
