postgres:
  user: "khan_perf"
  dbName: "khan_perf"
  host: "localhost"
  port: 5433
  sslMode: "disable"

mongodb:
  enabled: true
  url: mongodb://localhost:27017
  databaseName: "khan"
  collectionTemplate: "clans_%s"

search:
  pageSize: 10

jaeger:
  disabled: true
  samplingProbability: 0.001
  serviceName: "khan"

extensions:
  dogstatsd:
    host: localhost:8125
    prefix: khan.
    tags_prefix: ""
    rate: 1
