postgres:
  user: "khan_test"
  dbName: "khan_test"
  host: "localhost"
  port: 5433
  sslMode: "disable"

elasticsearch:
  host: "localhost"
  enabled: true
  port: 9200
  sniff: false
  index: "khan"

mongodb:
  enabled: true
  url: mongodb://localhost:27017
  databaseName: "khan"
  collectionTemplate: "clans_%s"

khan:
  maxPendingInvites: -1
  defaultCooldownBeforeInvite: 0
  defaultCooldownBeforeApply: 3600

search:
  pageSize: 10

healthcheck:
  workingText: "WORKING"

webhooks:
  timeout: 500

jaeger:
  disabled: false
  samplingProbability: 1.0
  serviceName: "khan"

redis:
  host: 0.0.0.0
  port: 50505
  database: 0
  pool: 30
  password: ""

webhooks:
  timeout: 2
  workers: 5
  statsPort: 9999
  runStats: false
  logToBuf: true

extensions:
  dogstatsd:
    host: localhost:8125
    prefix: khan.
    tags_prefix: ""
    rate: 1

security:
  encryptionKey: "00000000000000000000000000000000"
