version: '2'

services:
  postgres:
    container_name: khan_postgres_1
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  elasticsearch:
    container_name: khan_elasticsearch_1
    image: elasticsearch:6.8.14
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
  redis:
    container_name: khan_redis_1
    image: redis
    ports:
      - "50505:6379"
  mongo:
    container_name: khan_mongo_1
    image: mongo
    ports:
      - "27017:27017"
